Pipe fifo file removal
syslog-ng/syslog-ng.github.io pull request #121
Opened 2024-08-22 10:38 UTC by zsoltgyulai94

Added note about required restart when making a new fifo file.

2024-08-22 11:10 UTC, zsoltgyulai94 commented on doc/_admin-guide/060_Sources/110_Pipe/README.md
> +**NOTE:** If the `fifo` file is deleted, syslog-ng OSE automatically recreates it. When a new `pipe()` is created, syslog-ng OSE continues to use the old file until the system is restarted.
Thanks for clarifying, I modified the note. Hopefully it's correct now.

2024-08-22 11:16 UTC, kovgeri01 submitted a review, later dismissed

2024-08-23 13:40 UTC, kovgeri01 commented on doc/_admin-guide/060_Sources/110_Pipe/README.md
> +**NOTE:** If the `fifo` file is deleted, and the user creates a new one, syslog-ng OSE will still attempt to access the old file until the system is restarted. Make sure to restart syslog-ng OSE afte
```suggestion
**NOTE:** If the `fifo` file is deleted, and the user creates a new one, syslog-ng OSE will still attempt to access the old file until syslog-ng is restarted. Make sure to restart syslog-ng OSE after creating a new `fifo` file.
```

2024-08-23 13:41 UTC, kovgeri01 commented on doc/_admin-guide/060_Sources/110_Pipe/README.md
> +**NOTE:** If the `fifo` file is deleted, and the user creates a new one, syslog-ng OSE will still attempt to access the old file until the system is restarted. Make sure to restart syslog-ng OSE afte
sorry i missed this, added a suggestion to fix it

2024-08-26 13:45 UTC, mrgarris0n requested changes

2024-08-26 13:45 UTC, mrgarris0n commented on doc/_admin-guide/060_Sources/110_Pipe/README.md
> +**NOTE:** If the `fifo` file is deleted, and the user creates a new one, syslog-ng OSE will still attempt to access the old file until syslog-ng is restarted. Make sure to restart syslog-ng OSE after
```suggestion
**NOTE:** If the `fifo` file is deleted, and the user creates a new one, {{ site.product.short_name }} will still attempt to access the old file until {{ site.product.short_name }} is restarted. Make sure to restart {{ site.product.short_name }} after creating a new `fifo` file.
```

2025-02-12 11:11 UTC, zsoltgyulai94 commented
All issues seem to have been resolved one way or another, can we merge this? @mrgarris0n @kovgeri01

2025-02-19 15:32 UTC, mrgarris0n approved these changes

2025-02-19 15:57 UTC, merged