system() and systemd-journal() sources
syslog-ng/syslog-ng.github.io pull request #150
Opened 2024-10-24 10:43 UTC by zsoltgyulai94

2024-11-25 16:08 UTC, mrgarris0n requested changes

2024-11-25 16:08 UTC, mrgarris0n commented on doc/_admin-guide/060_Sources/180_System/README.md
> +|              |If syslog-ng OSE is running in a jail or a Linux Container (LXC), it will not read from the `/dev/kmsg` or `/proc/kmsg` files.
Please use {{ site.product.short_name }} here as well.
Also, this seems like a duplicated line.

2025-02-03 11:03 UTC, zsoltgyulai94 commented on doc/_admin-guide/060_Sources/180_System/README.md
> +|              |If syslog-ng OSE is running in a jail or a Linux Container (LXC), it will not read from the `/dev/kmsg` or `/proc/kmsg` files.
Thanks, removed duplicate line, and used variable.

2025-02-04 08:28 UTC, mrgarris0n approved these changes

2025-02-04 09:24 UTC, merged