Elasticsearch-datastream
syslog-ng/syslog-ng.github.io pull request #152
Opened 2024-11-25 11:28 UTC by zsoltgyulai94

Signed-off-by: Zsolt Gyulai (zgyulai) <zsolt.gyulai@quest.com>

Added new elasticsearch-datastream destination.

2024-11-25 15:54 UTC, mrgarris0n commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +```
missing newline

2024-11-25 15:55 UTC, mrgarris0n commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +    From syslog-ng OSE 4.8 and later versions, you  can send messages and metrics to [Elasticsearch data streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html) to
Please store links in _data/external_links.yml file and refer them by ID here.

2024-11-25 15:55 UTC, mrgarris0n commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +This driver is a reusable configuration snippet configured to send log messages using the http() driver using a template. You can find the source of this configuration snippet on [GitHub](https://git
Please store links in _data/external_links.yml file and refer them by ID here.

2024-11-25 15:57 UTC, mrgarris0n requested changes

2024-11-25 15:57 UTC, mrgarris0n commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +    From syslog-ng OSE 4.8 and later versions, you  can send messages and metrics to [Elasticsearch data streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html) to
Please use product.short_name here

2025-02-03 11:26 UTC, zsoltgyulai94 commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +```
Updates included in last commit.

2025-02-03 11:26 UTC, zsoltgyulai94 commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +    From syslog-ng OSE 4.8 and later versions, you  can send messages and metrics to [Elasticsearch data streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html) to
Updates included in last commit.

2025-02-03 11:26 UTC, zsoltgyulai94 commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +This driver is a reusable configuration snippet configured to send log messages using the http() driver using a template. You can find the source of this configuration snippet on [GitHub](https://git
Updates included in last commit.

2025-02-03 11:26 UTC, zsoltgyulai94 commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +    From syslog-ng OSE 4.8 and later versions, you  can send messages and metrics to [Elasticsearch data streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html) to
Updates included in last commit.

2025-02-04 09:38 UTC, zsoltgyulai94 commented on doc/_admin-guide/070_Destinations/035_elasticsearch-datastream/README.md
> +This driver is a reusable configuration snippet configured to send log messages using the http() driver using a template. You can find the source of this configuration snippet on [GitHub](https://git
Also udjusted link to refer to the right repo.

2025-02-04 12:28 UTC, merged