External links refactor
syslog-ng/syslog-ng.github.io pull request #47
Opened 2024-05-17 15:25 UTC by mrgarris0n

Fixes: #7 

Added missing links to external_links.yml file
Added some guidelines to yml
Created logical grouping and alphabetical order in yml
Eliminated hardwired URLs from admin guide
Fixed some missing id-s

2024-05-21 16:07 UTC, HofiOne requested changes

2024-05-21 16:07 UTC, HofiOne commented on doc/_admin-guide/200_About/README.md
> +access the Support Portal [[here|oi-support-serv]].
to eliminate here maybe we could use:


Technical support for One Identity customers with a valid maintenance contract, as well as for those using a trial version, is available via our [[Support Portal|oi-support-serv]].

2024-05-22 15:51 UTC, HofiOne requested changes

2024-05-22 15:51 UTC, HofiOne commented on doc/_admin-guide/190_The_syslog-ng_manual_pages/010_syslog-ng_conf.md
>  |amqp()|           Publishes messages using the AMQP (Advanced Message Queuing Protocol).
i was wondering if it broke anything adding | to the pattern separators to find title occurrences in these table declarations as well

2024-05-23 10:36 UTC, mrgarris0n commented on doc/_admin-guide/020_The_concepts_of_syslog-ng/007_The_structure_of_a_log_message/001_IETF_syslog_messages.md
> +    IETF-syslog protocol.
"IETF-syslog" is a more inclusive variant than "IETF-syslog protocol", but I'll handle this in a separate PR, with link aliases.

2024-05-23 10:57 UTC, mrgarris0n commented on doc/_admin-guide/060_Sources/025_Arr_logs/README.md
> +This driver is a reusable configuration snippet. For details on using or writing such configuration snippets, see Reusing configuration blocks. The source of the Arr configuration snippet can be acce
This is only for the config file links.

2024-05-23 11:14 UTC, mrgarris0n commented on _includes/doc/admin-guide/options/gRPC-keep-alive.md
> +This option configures the forwarding of gRPC keepalive pings in syslog-ng OSE.
Will create a link alias for that in a separate PR

2024-05-23 11:35 UTC, mrgarris0n commented on doc/_admin-guide/120_Parser/021_Checkpoint_parser.md
>  improve the parser.
#56

2024-05-24 11:29 UTC, HofiOne approved these changes

2024-05-24 11:30 UTC, merged